# Generated by Django 2.2 on 2023-11-20 17:05

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriesModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(default=None)),
                ('status', models.CharField(choices=[('active', 'ACTIVE'), ('deactivate', 'DEACTIVATE')], default='deactivate', max_length=100)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2023, 11, 20, 23, 35, 33, 290020))),
            ],
        ),
        migrations.CreateModel(
            name='FilesModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('file', models.FileField(default=None, upload_to='')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2023, 11, 20, 23, 35, 33, 290697))),
            ],
        ),
        migrations.CreateModel(
            name='ItemsModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('purchase_price', models.IntegerField()),
                ('price', models.IntegerField(default=None)),
                ('qty', models.IntegerField(default=None)),
                ('barcode', models.IntegerField(default=None)),
                ('status', models.CharField(choices=[('deactivate', 'DEACTIVATE'), ('active', 'ACTIVE')], default='deactivate', max_length=50)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2023, 11, 20, 23, 35, 33, 291481))),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_store.CategoriesModel')),
                ('files', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_store.FilesModel')),
            ],
        ),
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('deactivate', 'DEACTIVATE'), ('active', 'ACTIVE')], default='deactivate', max_length=50)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2023, 11, 20, 23, 35, 33, 292309))),
            ],
        ),
        migrations.CreateModel(
            name='RolesModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2023, 11, 20, 23, 35, 33, 295090))),
            ],
        ),
        migrations.CreateModel(
            name='ShopModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('phone', models.IntegerField(default=None)),
                ('open', models.DateTimeField(default=datetime.datetime(2023, 11, 20, 23, 35, 33, 293813))),
                ('close', models.DateTimeField(default=datetime.datetime(2023, 11, 20, 23, 35, 33, 293842))),
                ('status', models.CharField(choices=[('deactivate', 'DEACTIVATE'), ('active', 'ACTIVE')], default='deactivate', max_length=50)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2023, 11, 20, 23, 35, 33, 293890))),
            ],
        ),
        migrations.CreateModel(
            name='UsersModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateTimeField(default=datetime.datetime(2005, 11, 20, 5, 5, 33, 295438, tzinfo=utc))),
                ('nrc_number', models.CharField(default='##/A B C(C)/######', max_length=30)),
                ('address', models.TextField()),
                ('phone', models.CharField(default='09 123 456 789', help_text='Enter phone number in the format: 09 123 456 789', max_length=15)),
                ('email', models.EmailField(default='username@gmail.com', max_length=254)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2023, 11, 20, 23, 35, 33, 295533))),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_store.RolesModel')),
            ],
        ),
        migrations.CreateModel(
            name='PermissionsModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2023, 11, 20, 23, 35, 33, 295990))),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_store.RolesModel')),
            ],
        ),
        migrations.CreateModel(
            name='Order_ItemsModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('qty', models.IntegerField(default=None)),
                ('total', models.IntegerField(default=None)),
                ('profix', models.IntegerField(default=None)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2023, 11, 20, 23, 35, 33, 292963))),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_store.ItemsModel')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_store.OrderModel')),
            ],
        ),
        migrations.CreateModel(
            name='InvoicesModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total_qty', models.IntegerField(default=None)),
                ('subtotal', models.IntegerField(default=None)),
                ('tax', models.IntegerField(default=None)),
                ('discount', models.IntegerField(default=None)),
                ('credit', models.IntegerField(default=None)),
                ('total_amount', models.IntegerField(default=None)),
                ('is_delivery', models.IntegerField(default=None)),
                ('charge', models.IntegerField(default=None)),
                ('refund', models.IntegerField(default=None)),
                ('status', models.CharField(choices=[('deactivate', 'DEACTIVATE'), ('active', 'ACTIVE')], default='deactivate', max_length=50)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2023, 11, 20, 23, 35, 33, 294576))),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_store.OrderModel')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_store.ShopModel')),
            ],
        ),
    ]
