# Generated by Django 3.2.23 on 2023-11-27 14:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('my_store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filesmodel',
            name='name',
        ),
        migrations.AlterField(
            model_name='categoriesmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 27, 21, 11, 56, 934717)),
        ),
        migrations.AlterField(
            model_name='filesmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 27, 21, 11, 56, 934717)),
        ),
        migrations.AlterField(
            model_name='invoicesmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 27, 21, 11, 56, 936717)),
        ),
        migrations.AlterField(
            model_name='invoicesmodel',
            name='status',
            field=models.CharField(choices=[('active', 'ACTIVE'), ('deactivate', 'DEACTIVATE')], default='deactivate', max_length=50),
        ),
        migrations.AlterField(
            model_name='itemsmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 27, 21, 11, 56, 935718)),
        ),
        migrations.AlterField(
            model_name='itemsmodel',
            name='status',
            field=models.CharField(choices=[('active', 'ACTIVE'), ('deactivate', 'DEACTIVATE')], default='deactivate', max_length=50),
        ),
        migrations.AlterField(
            model_name='order_itemsmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 27, 21, 11, 56, 935718)),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 27, 21, 11, 56, 935718)),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='status',
            field=models.CharField(choices=[('active', 'ACTIVE'), ('deactivate', 'DEACTIVATE')], default='deactivate', max_length=50),
        ),
        migrations.AlterField(
            model_name='permissionsmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 27, 21, 11, 56, 936717)),
        ),
        migrations.AlterField(
            model_name='rolesmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 27, 21, 11, 56, 936717)),
        ),
        migrations.AlterField(
            model_name='shopmodel',
            name='close',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 27, 21, 11, 56, 935718)),
        ),
        migrations.AlterField(
            model_name='shopmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 27, 21, 11, 56, 935718)),
        ),
        migrations.AlterField(
            model_name='shopmodel',
            name='open',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 27, 21, 11, 56, 935718)),
        ),
        migrations.AlterField(
            model_name='shopmodel',
            name='status',
            field=models.CharField(choices=[('active', 'ACTIVE'), ('deactivate', 'DEACTIVATE')], default='deactivate', max_length=50),
        ),
        migrations.AlterField(
            model_name='usersmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 27, 21, 11, 56, 936717)),
        ),
        migrations.AlterField(
            model_name='usersmodel',
            name='date_of_birth',
            field=models.DateTimeField(default=datetime.datetime(2005, 11, 27, 2, 41, 56, 936717, tzinfo=utc)),
        ),
    ]
