# Generated by Django 3.2.23 on 2024-01-04 07:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('my_store', '0002_auto_20231127_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriesmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 4, 14, 0, 51, 116779)),
        ),
        migrations.AlterField(
            model_name='filesmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 4, 14, 0, 51, 116779)),
        ),
        migrations.AlterField(
            model_name='invoicesmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 4, 14, 0, 51, 116779)),
        ),
        migrations.AlterField(
            model_name='invoicesmodel',
            name='order',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='itemsmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 4, 14, 0, 51, 116779)),
        ),
        migrations.AlterField(
            model_name='order_itemsmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 4, 14, 0, 51, 116779)),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 4, 14, 0, 51, 116779)),
        ),
        migrations.AlterField(
            model_name='permissionsmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 4, 14, 0, 51, 116779)),
        ),
        migrations.AlterField(
            model_name='rolesmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 4, 14, 0, 51, 116779)),
        ),
        migrations.AlterField(
            model_name='shopmodel',
            name='close',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 4, 14, 0, 51, 116779)),
        ),
        migrations.AlterField(
            model_name='shopmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 4, 14, 0, 51, 116779)),
        ),
        migrations.AlterField(
            model_name='shopmodel',
            name='open',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 4, 14, 0, 51, 116779)),
        ),
        migrations.AlterField(
            model_name='usersmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 4, 14, 0, 51, 116779)),
        ),
        migrations.AlterField(
            model_name='usersmodel',
            name='date_of_birth',
            field=models.DateTimeField(default=datetime.datetime(2006, 1, 3, 19, 30, 51, 116779, tzinfo=utc)),
        ),
    ]
